Repository AICoE/prometheus-flatliner, pull requests merged in 2019-10, with the labels that each got.

#99 Added kebechet support
  .thoth.yaml
Labels: approved, size/S

#103 Update .zuul.yaml
  .zuul.yaml
Labels: approved, size/XS

#102 Add an ansible playbook for openshift deployment
  README.md
  playbooks/flatliner.yaml
  playbooks/templates/flatliner-openshift-objects.yaml
  playbooks/vars/common-vars.yaml
  playbooks/vars/flatliner-vars.yaml
Labels: approved, size/L
